[package]
name = "molyidev/butler"
version = "1.2.0"
description = "Memory management library."
authors = ["Molyi"]
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/MolyiDev/Butler"
license = "MIT"
realm = "shared"
exclude = ["**"]
include = ["wally.toml", "default.project.json", "README.md", "LICENSE", "src", "src/**"]

[dependencies]
